spring.application.name=cms

# Server Port
server.port=8080

# MariaDB Connection Details
spring.datasource.url=jdbc:mariadb://localhost:3306/cms_db
spring.datasource.username=root
spring.datasource.password=12345

# Hibernate / JPA Settings
# 'update' automatically creates/updates the tables based on your @Entity classes!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true

# Allow uploading large files (Excel files can get big)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
